version: 2
updates:
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/single-commit'
    schedule:
      interval: 'weekly'
    groups:
      single-commit-production:
        dependency-type: 'production'
    assignees:
      - 'algo7'